// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djzfznabhrwosigvaqck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqemZ6bmFiaHJ3b3NpZ3ZhcWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NzI0ODAsImV4cCI6MjA1ODI0ODQ4MH0.cgmXnvFOcWtjVvSl3-By49e-iof2d-jMGWBPlBfrsVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);